<a href="https://colab.research.google.com/github/eda426/-gen-alan-hesaplama/blob/main/7_atolyeOdev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [8]:
# 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

# Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

np.array([1,2,3,4],dtype="int")
arr=np.array([1,2,3,4],dtype="int")
print(arr.ndim)
print(arr.size)


1
4


In [9]:
# 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

# İki boyutlu array:
# [[1,2,6,7],
# [4,3,9,5]]

# Üç boyutlu array:
# [[[7,5,14],[21,8,11]],
# [[8,6,20],[14,3,9]]]

arr2=np.array([[1,2,6,7],[4,3,9,5]])
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(arr2.ndim,arr2.size,arr2.shape)
print(arr3.ndim,arr3.size,arr3.shape)

2 8 (2, 4)
3 12 (2, 2, 3)


In [13]:
# 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

# İki boyutlu arraydaki 2 elemanına ulaşalım.

# İki boyutlu arraydaki 7 elemanına ulaşalım.

# Üç boyutlu arraydaki 9 elemanına ulaşalım.

# Üç boyutlu arraydaki 5 elemanına ulaşalım.

print(arr2[1,1])
print(arr2[0,3])
print(arr3[1,1,2])
print(arr3[0,0,1])


3
7
9
5


In [18]:
# 4. Arrayler üzerinde slicing işlemi uygulayalım.

# İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.
print(arr2[0,1:3])

# İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.
print(arr2[1,1:4])
# Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.
print(arr3[0,1,:])
# Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.
print(arr3[1,0,1:3])


[2 6]
[3 9 5]
[21  8 11]
[ 6 20]


In [19]:
#5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim

arr_zeros = np.zeros((5, 3), dtype=int)
arr_ones = np.ones((5, 3), dtype=int)
satir_bazinda = np.concatenate((arr_zeros, arr_ones), axis=0)
sutun_bazinda = np.concatenate((arr_zeros, arr_ones), axis=1)

print("Sıfırlar:\n", arr_zeros)
print("\nBirler:\n", arr_ones)
print("\nSatır bazında birleştirme (10x3):\n", satir_bazinda)
print("\nSütun bazında birleştirme (5x6):\n", sutun_bazinda)

Sıfırlar:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Birler:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır bazında birleştirme (10x3):
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirme (5x6):
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
