<a href="https://colab.research.google.com/github/eda426/-gen-alan-hesaplama/blob/main/verianalizive_yapayzekat%C3%BCmderslerim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# in Operatörü: Bir değerin bir veri yapısında bulunup bulunmadığını kontrol eder.

In [ ]:
atolye="yazılımla güçlenen kadınlar"
atolye

'yazılımla güçlenen kadınlar'

In [ ]:
"l" in atolye

True

In [ ]:
"v" in atolye

False

In [ ]:
len(286382468246)

TypeError: object of type 'int' has no len()

In [ ]:
len("286382468246")#len fonksiyonu nesnenin uzunluğunu veya eleman sayısını döndürür

12

In [ ]:
tc_no="16729493792"
len(tc_no)

11

In [ ]:
#indexleme (indeksleme), Python'da bir veri yapısının (liste, tuple, dize vb.) belirli bir öğesine erişmek için kullanılan bir kavramdır.

harfler="acrtjhgmjmgm"
harfler


'acrtjhgmjmgm'

In [ ]:
harfler[5]

'h'

In [ ]:
#slice dilimleme işlemidir
harfler[0:5]

'acrtj'

In [ ]:
#input kullanıcıdan veri girilmesini sağlar
name=input("isminiz nedir?")
print(name)

isminiz nedir?eda
eda


üyelik operatör

In [ ]:
##üçüncü atölyee koşullar ve döngüler
x=7

if x>0:
 print(x,"pozitiftir")


7 pozitiftir


In [ ]:
sayi=int(input("1 ile 15 arasında bir sayı giriniz:"))
print("girdiğiniz sayı:",sayi)

1 ile 15 arasında bir sayı giriniz:8
girdiğiniz sayı: 8


In [ ]:
# eğer ki sayı 15'den büyük olursa büyük sayı girdiğinin uyarısını versin.

if sayi>15:
   print("büyük sayı girdiniz")

In [ ]:
# sayı eğer ki negatif ise negatif sayı girdiniz uyarısı versin
if sayi<0:
   print("negatif sayı girdiniz")

In [ ]:
sayi=int(input("1 ile 15 arasında bir sayı giriniz:"))
if sayi>15:
  print("büyük sayı girdiniz")
elif sayi<0:
  print("negatif sayı girdiniz")



1 ile 15 arasında bir sayı giriniz:-2
negatif sayı girdiniz


In [ ]:
sayi=int(input("1 ile 100 arasında bir sayı giriniz:"))
if sayi>100:
  print("büyük sayı girdiniz")
elif sayi<0:
  print("negatif sayı girdiniz")
else:
  print("sayı 1 ile 100 arasında olmalı!")

1 ile 100 arasında bir sayı giriniz:101
büyük sayı girdiniz


In [ ]:
#Bir oyunda toplanan skorların toplam sonucunu çok iyi, iyi, kötü olarak üç kategoriye ayıralım.

#en fazla 100 olabilir.

#40 : Kötü 40-70 : İyi 70-100 : Çok iyi
skor=int(input("oyunda topladığınız skoru giriniz:"))
if skor<=40:
 print("kötü daha fazla sayı toplamalısın")
elif skor<=70:
 print("iyi skor!")
elif skor<=100:
  print("tebrikler çok iyi skor")
else:
  print("geçersiz değer")

oyunda topladığınız skoru giriniz:65
iyi skor!


In [ ]:
#Bir hava durumu uygulamasında, kullanıcıdan günün sıcaklığı (santigrat cinsinden) alınarak hava durumu kategorisi belirlenmek isteniyor.

#Kategoriler şu şekilde olsun:

#0°C ve altı: Çok soğuk 1°C - 15°C arası: Serin 16°C - 30°C arası: Ilık 31°C ve üzeri: Sıcak Kullanıcıdan bir sıcaklık değeri alınacak ve
#bu değere göre uygun mesaj yazdırılacak.

sicaklik=float(input("hava sıcaklığını( (santigrat cinsinden)) giriniz:"))
if sicaklik<=0:
 print("Çok soğuk")
elif 1<=sicaklik<=15:
  print("Serin")
elif 16<=sicaklik<=30:
  print("Ilık")
else:
  print("Sıcak")

hava sıcaklığını( (santigrat cinsinden)) giriniz:16
Ilık


In [ ]:
a=1

while a<=10:
  print("Merhaba")
  a+=1

Merhaba
Merhaba
Merhaba
Merhaba
Merhaba
Merhaba
Merhaba
Merhaba
Merhaba
Merhaba


In [ ]:

a=1

while a<=10:
  print(a)
  a+=1



1
2
3
4
5
6
7
8
9
10


In [ ]:
#0'dan 10'a kadar çift sayıları ekrana yazıralım.
a=0
while a<=10:
 if a%2==0:
   print(a)
 a+=1

0
2
4
6
8
10


In [ ]:
#kahve makineleri, kullanıcı bir seçim yapsın, 2 ve 4 arasındaki ürünler yok.
while True:
  secim=int(input("Kahve seçimi yapınız: (0-Çıkış,2-4-Ürün yok)"))
  if secim==0:
    print("Çıkış yapılıyor..")
    break
  elif 2<=secim<=4:
    print("BU ürün mevcut değildir")
    pass
  else:
    print("Siparişiniz alındı.Afiyet olsun.")



Kahve seçimi yapınız: (0-Çıkış,2-4-Ürün yok)5
Siparişiniz alındı.Afiyet olsun.
Kahve seçimi yapınız: (0-Çıkış,2-4-Ürün yok)3
BU ürün mevcut değildir
Kahve seçimi yapınız: (0-Çıkış,2-4-Ürün yok)0
Çıkış yapılıyor..


In [ ]:
#for döngüsü her elaman için çalışacak olan döngü çeşididir
sozcuk="Matematik"
for harf in sozcuk:
  print(harf)



M
a
t
e
m
a
t
i
k


In [ ]:
for sayi in range(10):
  print(sayi)


0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(4,9):
  print(i)

4
5
6
7
8


In [ ]:
for i in range(10,1,-2):
  print(i)

10
8
6
4
2


In [ ]:
for i in range(20):
  if i%2==1:
    pass
  else:
    print(i)

0
2
4
6
8
10
12
14
16
18


In [ ]:
#FONKSİYONLAR 4.ATÖLYEM
def ekle(yas):
  yeni_yas=yas+1
  print(str(yas) + " bir yaş daha alırsa " + str(yeni_yas) + " olur ")

ekle(29)



29 bir yaş daha alırsa 30 olur 


In [ ]:
#mesafe hesaplama
def mesafe_hesapla(hız,süre):
  mesafe=hız*süre
  print(" Araç saatte " + str(hız) + " km hızla " + str(süre) + " saatte " + str(mesafe) + " km yol gider.")

mesafe_hesapla(145,5)

 Araç saatte 145 km hızla 5 saatte 725 km yol gider.


In [ ]:
def ekle(sayi):
  yeni_sayi=sayi+1
  print("{} sayısına 1 eklenirse {} sayısı elde edilir".format(sayi,yeni_sayi))

ekle(398)

398 sayısına 1 eklenirse 399 sayısı elde edilir


In [ ]:
#f-string, Python 3.6 ve sonrasında tanıtılan bir özelliktir ve değişkenleri ifadeleri string içerisinde daha okunabilir ve
#kolay bir şekilde eklemenizi sağlar. f-string kullanarak, string içinde değişkenlerin değerlerini veya ifadelerin sonuçlarını eklemek için
#süslü parantezler {} kullanırız. f-string, f veya F karakteri ile başlar.

def ekle(sayi):
  yeni_sayi=sayi+1
  print(f"{sayi} sayısına 1 eklenirse {yeni_sayi} elde ederiz")

ekle(78898)


78898 sayısına 1 eklenirse 78899 elde ederiz


In [ ]:
isim="Eda"
soyisim="özdemir kurt"
print(f"benim adım {isim} soyadım {soyisim}")

benim adım Eda soyadım özdemir kurt


In [ ]:
#fonksiyon örneği yazalım.
#portakal sıkma makinesini bir fonksiyona dönüştürelim.

def portakal_suyu_makinası(portakal):
  portakal_suyu=portakal*0.5
  print(f"{portakal_suyu} bardak portakal suyu elde ettiniz")

portakal_sayisi=int(input("kaç portakal var?"))
portakal_suyu_makinası(portakal_sayisi)


kaç portakal var?9
4.5 bardak portakal suyu elde ettiniz


In [ ]:
#üç sayı tanımlama ve karesini print ile yazdıralım
def hesaplama(sayi):
  print(str(sayi) + " sayısının karesi " + str(sayi**2)  + " , küpü ise " + str(sayi**3) + " olacaktır")

hesaplama(9)
hesaplama(4)

9 sayısının karesi 81 , küpü ise 729 olacaktır
4 sayısının karesi 16 , küpü ise 64 olacaktır


In [ ]:
def kare_hesaplama(sayi):
    sonuc = sayi**2
    print(sonuc)
    return sonuc # Bu satır fonksiyonunun sonucunu döndürür

kare_hesaplama(2) * 3
kare_hesaplama(2) * "Büşra "

4
4


'Büşra Büşra Büşra Büşra '

In [ ]:
# Python’da dinamik programlama yaparken işini kolaylaştırır.

# 🔹 Önce Tanımlar

# *args (tek yıldız) Birden fazla konum (sırasız) argümanı alır. Tüm gelen değerleri tuple içinde saklar.

# **kwargs (çift yıldız) Anahtar=değer şeklinde gelen argümanları alır. Tüm gelen değerleri dictionary (sözlük) içinde saklar.

# 🎯 Neden Bu Kadar Önemli?

# Sen bir fonksiyon yazarken kaç tane değer geleceğini bilmiyorsan, veya kullanıcıdan gelen veri değişkenlik gösteriyorsa, bu yöntemleri kullanırsın.

def topla(*args):
  toplam=0
  for sayi in args:
    toplam+=sayi
  print("toplam:",toplam)

topla(3,5)
topla(3,5,7)
topla(3,5,7,9)



toplam: 8
toplam: 15
toplam: 24


In [ ]:
#5.ATÖLYEM

Listeler için kullanılabilecek metodlar
Bir liste üzerinde doğrudan çalışır ve genellikle listeyi yerinde (in-place) değiştirirler. (liste.metod() şeklinde kullanılırlar).

.append(): Liste sonuna eleman ekler.

.extend(): Bir listeye başka bir listenin sonuna ekler.

.insert(): Belirtilen bir konuma eleman ekler.

.remove(): Belirtilen değere sahip elemanı listeden çıkarır.

.pop(): Belirtilen konumdaki elemanı listeden çıkarır ve bu elemanı döndürür.

 Konum belirtilmezse son elemanı çıkarır ve döndürür.

.clear(): Listedeki tüm elemanları kaldırır.

.index(): Belirtilen değere sahip ilk elemanın konumunu döndürür.

.count(): Belirtilen değerin listede kaç kez geçtiğini döndürür.

.sort(): Liste elemanlarını küçükten büyüğe sıralar.

.reverse(): Liste elemanlarını tersine çevirir.

.copy(): Listenin bir kopyasını döndürür.

Listelerde kullanılabilecek yerleşik metodlar

Yerleşik fonksiyonlar olarak Python dilinin bir parçasıdırlar( fonksiyon(adı) şeklinde kullanılırlar).

len(): Herhangi bir iterable'ın (listeler, stringler, tuple'lar, vb.) uzunluğunu döndürür.

min(): Herhangi bir iterable'daki en küçük elemanı döndürür

max(): Herhangi bir iterable'daki en büyük elemanı döndürür

split(): Stringlerde kullanılır ve belirtilen ayırıcıya göre stringi böler ve bir liste döndürür.

sum(): Bir iterable'daki elemanların toplamını döndürür.

sorted(): Bir iterable'ı sıralar ve yeni bir sıralanmış liste döndürür.

In [ ]:
#Basit sayılardan oluşan bir liste yapalım.

my_list=[4, 6, 7, 11, 13, 77, 44]
my_list

[4, 6, 7, 11, 13, 77, 44]

In [ ]:
type(my_list)

list

In [ ]:
# listede 0. indexe erişelim.
my_list[0]
# listede -1. indexe erişelim
my_list[-1]
# listede 2 ile 4 indexe erişelim.
my_list[2:5]

[7, 11, 13]

In [ ]:
#Listeler değiştirilebilir olduğu için elemanları değiştirelim.
my_list

[4, 6, 7, 11, 13, 77, 44]

In [ ]:
my_list[2]="veri bilimi"


In [ ]:
print(my_list)

[4, 6, 'veri bilimi', 11, 13, 77, 44]


In [ ]:
# 5. indexi python stringi ile değiştirelim
my_list[5]="Pyhton"
print(my_list)

[4, 6, 'veri bilimi', 11, 13, 'Pyhton', 44]


In [ ]:
#Liste içinde liste bulunabilir.
my_list2 = ["Elma", "Karpuz", 5, ["üzüm", 1.2], [2, 4.1, 5]]
my_list2

['Elma', 'Karpuz', 5, ['üzüm', 1.2], [2, 4.1, 5]]

In [ ]:
# Üzüm ifadesine ulaşalım. Yani liste içindeki listenin elemanına erişelim.
my_list2[3][0]

'üzüm'

In [ ]:
# my_list2 listesinde 4.1 erişelim.
my_list2[4][1]

4.1

In [ ]:
# split() fonksiyonu stringlerle çalışır. Split() fonksiyonu belirtilen bir ayraç(varsayılan olarak boşluk karakteri) ile böler
# ve böldüğü parçaları bir liste olarak döndürür. Özellikle metin işleme ve veri analizlerinde sıkça kullanılır.
atolye = "Yazılımla Güçlenen Kadınlar Veri Bilimi ve Yapay Zeka"
atolye_list=atolye.split()
atolye_list

['Yazılımla', 'Güçlenen', 'Kadınlar', 'Veri', 'Bilimi', 've', 'Yapay', 'Zeka']

In [ ]:
meyveler = "Üzüm, Karpuz, Muz, Çilek, Elma"
meyveler_list = meyveler.split(",")
meyveler_list

['Üzüm', ' Karpuz', ' Muz', ' Çilek', ' Elma']

In [ ]:
#len() fonksiyonu sadece stringlerin karakter uzunluğunu değil, listelerin içindeki elemanların sayısını da tespit edebilir.
atolye_list

['Yazılımla', 'Güçlenen', 'Kadınlar', 'Veri', 'Bilimi', 've', 'Yapay', 'Zeka']

In [ ]:
len(atolye_list)

8

In [ ]:
sayilar=1,4,5,6
x=list(sayilar)
x

[1, 4, 5, 6]

In [ ]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#bir liste oluşturup, listenin elemanı kadar range metodu ile sayılarını alt alta yazdıralım.
meyveler=["Elma","Armut","Karpuz","Kivi","Muz", "Çilek", "Kavun"]
for i in range(0,len(meyveler)):
  print(i)

0
1
2
3
4
5
6


In [ ]:
meyveler=["Elma","Armut","Karpuz","Kivi","Muz", "Çilek", "Kavun"]
for i in range(0,len(meyveler)):
  print(i,meyveler[i])

0 Elma
1 Armut
2 Karpuz
3 Kivi
4 Muz
5 Çilek
6 Kavun


In [ ]:
meyveler=["Elma","Armut","Karpuz","Kivi","Muz", "Çilek", "Kavun"]
for i in range(0,len(meyveler)):
  print(f"{i} - {meyveler[i]}")

0 - Elma
1 - Armut
2 - Karpuz
3 - Kivi
4 - Muz
5 - Çilek
6 - Kavun


In [ ]:
#append() metodu listeye yeni öğe eklemek için kullanılır.

my_list.append(" yapay zeka")
my_list

[4, 6, 'veri bilimi', 11, 13, 'Pyhton', 44, ' yapay zeka']

In [ ]:
#insert() metodu, Python'da listelere belirli bir konumda (indekste) yeni bir öğe eklemek için kullanılır.
cicek = ["manolya", "papatya", 4.2, "Gül", "Yasemin", 0]
cicek

['manolya', 'papatya', 4.2, 'Gül', 'Yasemin', 0]

In [ ]:
#2.indexe Nergis ifadesini ekleyelim.

cicek.insert(2,"Nergis")
cicek

['manolya', 'papatya', 'Nergis', 4.2, 'Gül', 'Yasemin', 0]

In [ ]:
#5. indexe 15 sayısını ekleyelim
cicek.insert(5,15)
cicek

['manolya', 'papatya', 'Nergis', 4.2, 'Gül', 15, 'Yasemin', 0]

In [ ]:
#extend() iki listeyi birbirine ekler.
sebze = ["Salatalık", "Patlıcan", "Kabak"]




In [ ]:
temizlik = ["Sabun", "Cif"]

In [ ]:
sebze.extend(temizlik)
sebze

['Salatalık', 'Patlıcan', 'Kabak', 'Sabun', 'Cif']

In [ ]:
temizlik.extend(sebze)
temizlik

['Sabun',
 'Cif',
 'Salatalık',
 'Patlıcan',
 'Kabak',
 'Sabun',
 'Cif',
 'Salatalık',
 'Patlıcan',
 'Kabak',
 'Sabun',
 'Cif']

In [ ]:
temizlik.remove('Sabun')
temizlik

['Cif',
 'Salatalık',
 'Patlıcan',
 'Kabak',
 'Cif',
 'Salatalık',
 'Patlıcan',
 'Kabak',
 'Sabun',
 'Cif']

In [ ]:
#sort() fonksiyonu, listedeki öğeleri sıralar
numbers = [4 ,9 ,2, 17, 3, 19, 5]
numbers

[4, 9, 2, 17, 3, 19, 5]

In [ ]:
#küçükten büyüğe sıralama
numbers.sort()
numbers

[2, 3, 4, 5, 9, 17, 19]

In [ ]:
#6.ATÖLYEM

In [ ]:
#Tuple'lar bir kez oluşturulduktan sonra değerleri değiştirilemez,silinemez ya da yeni değer eklenemez.
meyveler = ("armut", "Karpuz", "ayva", "portakal", "armut","muz")
meyveler

('armut', 'Karpuz', 'ayva', 'portakal', 'armut', 'muz')

In [ ]:
meyveler[1] = "Elma"

TypeError: 'tuple' object does not support item assignment

In [ ]:
meyveler = ("armut", "Karpuz", "ayva", "portakal", "armut","muz")
meyve = ("Elma",)
meyveler += meyve
meyveler

##Tek öğeli tuple oluştururken öğeden sonra
# virgül kullanılmalı yoksa python bunun tuple olduğunu anlamayacaktır.

('armut', 'Karpuz', 'ayva', 'portakal', 'armut', 'muz', 'Elma')

In [ ]:
#listeyi kümeye dönüştürelim.
meyveler=set(["Elma","ayva",9])
meyveler

{9, 'Elma', 'ayva'}

In [ ]:
#Set, her öğeden yalnızca bir tane içerir.
kume2 = {"Python", "Merhaba", 6.8, "Merhaba" , True}
kume2

{6.8, 'Merhaba', 'Python', True}

In [ ]:
kume2.add(22.3)
kume2

{22.3, 6.8, 'Merhaba', 'Python', True}

In [ ]:
# 7.ATÖLYEM


NumPy Kütüphanesi

Verimlilik: NumPy, büyük veri setleriyle çalışırken hesaplamaları hızlı ve etkili yapar.

Temel Kütüphane: Pandas, SciPy, scikit-learn gibi birçok kütüphane NumPy üzerine kuruludur.

Bellek Yönetimi: NumPy dizileri daha az bellek kullanır ve büyük veri setleriyle çalışırken performansı artırır.

Kolay Kullanım: Karmaşık matematiksel işlemleri basitleştirir ve kodu daha okunabilir hale getirir.

Topluluk ve Kaynaklar: NumPy'nın geniş bir topluluğu ve bolca öğretici kaynağı vardır.

Numpy, dizilerle çalışmak için kullanılır. Bunun yanında doğrusal cebir, matris gibi alanlarda kullanılır.


Yapı ve işlev olarak listelerle benzer olsada listelerden çok daha hızlıdırlar.

NumPy kütüphanesini indirme ve çalıştırma

!pip install numpy

import numpy as np

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#np.array() fonksiyonu, verilen bir Python listesi, tuple'ı veya başka bir dizi benzeri nesneyi alır ve bu nesneyi bir NumPy array'ine dönüştürür.

x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [ ]:
type(x)

numpy.ndarray

NumPy array'leri homojen veri tipine sahiptir, yani tüm elemanlar aynı veri tipinde olmalıdır.

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
#iki boyutlı
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array1 = np.array(36)
array2 = np.array([1,2,3,4])
array3 = np.array([[1,2,3],[4,5,6]])
array4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array1.ndim, array2.ndim, array3.ndim, array4.ndim

(0, 1, 2, 3)

In [ ]:
#1. katmandaki 0.satırdaki 2. indexe erişelim
array4[1,0,2]

np.int64(3)

In [ ]:
array4[1,1,1]

np.int64(5)

In [ ]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
array4[1,1,1]

np.int64(5)

In [ ]:
array2

array([1, 2, 3, 4])

In [ ]:
#array2 de 1, 2, 3'ü ekrana yazdıralım
array2[0:3]

array([1, 2, 3])

In [ ]:
array3#iki boyutlu

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#array3'de 3 ve 6. sütunu yazdıralım
array3[0:2,2]

array([3, 6])

In [ ]:
#array3'de 2 ve 5 sütununa erişin
array3[0:2,1]

array([2, 5])

In [ ]:

array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#1. Katmandaki [4, 5, 6]'ya erişelim
array4[0,1,0:3]

array([4, 5, 6])

In [ ]:
#2 ve 5'i ekrana yazdıralım
array4[1,0:2,1]

array([2, 5])

In [ ]:
#8.ATÖLYEM
# Pandas kütüphanesinin kullanım amacı anlatılır. Pandas’ta kullanılan series ve data frame veri tipleri anlatılır. Bu veri tiplerinin kullanım amacı ve özellikleri uygulamalı olarak anlatılır.

# Series oluşturma: Series tanımı yapılır ve eleman sayısına, index ve değer bilgisine, ulaşma yöntemleri örnekler ile gösterilir.

# Indexing ve slicing: Seriler üzerinde indexing ve slicing işlemleri örnekler üzerinden gösterilir.

# Dataframe oluşturma: Dataframe tanımı yapılır ve nasıl oluşturulduğu, sütun adı değiştirme örnekleri verilir. Index ve sütun bilgisine ulaşma örnekleri gösterilir.

# Indexing ve slicing: Dataframe üzerinde eleman seçmek için yöntemler gösterilir.

# Drop fonksiyonu: Silme işlemi yapmak için olduğu belirtilir ve örnekler ile gösterilir.

# loc ve iloc: Bu yapılar ile etikete dayalı ve indexe dayalı seçme işlemi örnekleri yapılır.

# Eleman seçme: Dataframe’deki istenen sütunda belirli değerlerin gösterimi yapılır.

# Concat fonksiyonu: Dataframe’leri birleştirmek için kullanıldığı örnekler üzerinden anlatılır. Birleştirme işleminin yöntemine göre kullanılması gereken parametreler anlatılı

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
seri=pd.Series([12, 33, 45, 50, 14, 22, 16, 20,  4])
seri

0    12
1    33
2    45
3    50
4    14
5    22
6    16
7    20
8     4
dtype: int64

In [ ]:
type(seri)

pandas.core.series.Series

In [ ]:
seri.tail(-2)

2    45
3    50
4    14
5    22
6    16
7    20
8     4
dtype: int64

In [ ]:
#2. index ile 4. index (dahil) aralaığını seçelim.
seri[2:5]

2    45
3    50
4    14
dtype: int64

In [ ]:
seri2 = pd.Series([2,4,6,8,10,12], index = ["a","b","c","d","e","f"])
seri2

a     2
b     4
c     6
d     8
e    10
f    12
dtype: int64

In [ ]:
#index çağırma
seri2["b"]

np.int64(4)

In [ ]:
seri2["a":"d"]

a    2
b    4
c    6
d    8
dtype: int64

In [ ]:
#Sözlük üzerinden bir seri oluşturalım.

sozluk={"kübra":25,
        "Melis": 22,
          "Ayşe":26

}
sozluk

{'kübra': 25, 'Melis': 22, 'Ayşe': 26}

In [ ]:
yeni_sozluk=pd.Series(sozluk)
yeni_sozluk

kübra    25
Melis    22
Ayşe     26
dtype: int64

In [ ]:
#array üzerinden bir seri oluşturalım.
import numpy as np
#maximum 50 sayıya kadar çıkabilen ve 6 değerlerden oluşan random bir aray oluşturun
random_seri=pd.Series(np.random.randint(45,51,size=6))
print(random_seri)


0    50
1    49
2    50
3    45
4    45
5    49
dtype: int64


In [2]:
#kütüphanelerin import edilmesi
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving jobs_in_data.csv to jobs_in_data.csv


In [4]:
#Veri çekme
df=pd.read_csv("jobs_in_data.csv")
df


work_year                 job_title                    job_category  \
0          2023      Data DevOps Engineer                Data Engineering   
1          2023            Data Architect  Data Architecture and Modeling   
2          2023            Data Architect  Data Architecture and Modeling   
3          2023            Data Scientist       Data Science and Research   
4          2023            Data Scientist       Data Science and Research   
...         ...                       ...                             ...   
9350       2021           Data Specialist    Data Management and Strategy   
9351       2020            Data Scientist       Data Science and Research   
9352       2021  Principal Data Scientist       Data Science and Research   
9353       2020            Data Scientist       Data Science and Research   
9354       2020     Business Data Analyst                   Data Analysis   

     salary_currency  salary  salary_in_usd employee_residence  \
0                EUR   88000          95012            Germany   
1                USD  186000         186000      United States   
2                USD   81800          81800      United States   
3                USD  212000         212000      United States   
4                USD   93300          93300      United States   
...              ...     ...            ...                ...   
9350             USD  165000         165000      United States   
9351             USD  412000         412000      United States   
9352             USD  151000         151000      United States   
9353             USD  105000         105000      United States   
9354             USD  100000         100000      United States   

     experience_level employment_type work_setting company_location  \
0           Mid-level       Full-time       Hybrid          Germany   
1              Senior       Full-time    In-person    United States   
2              Senior       Full-time    In-person    United States   
3              Senior       Full-time    In-person    United States   
4              Senior       Full-time    In-person    United States   
...               ...             ...          ...              ...   
9350           Senior       Full-time       Remote    United States   
9351           Senior       Full-time       Remote    United States   
9352        Mid-level       Full-time       Remote    United States   
9353      Entry-level       Full-time       Remote    United States   
9354      Entry-level        Contract       Remote    United States   

     company_size  
0               L  
1               M  
2               M  
3               M  
4               M  
...           ...  
9350            L  
9351            L  
9352            L  
9353            S  
9354            L  

[9355 rows x 12 columns]

In [5]:
#ilk 5 satırına göz gezdirelim
df.head()

work_year             job_title                    job_category  \
0       2023  Data DevOps Engineer                Data Engineering   
1       2023        Data Architect  Data Architecture and Modeling   
2       2023        Data Architect  Data Architecture and Modeling   
3       2023        Data Scientist       Data Science and Research   
4       2023        Data Scientist       Data Science and Research   

  salary_currency  salary  salary_in_usd employee_residence experience_level  \
0             EUR   88000          95012            Germany        Mid-level   
1             USD  186000         186000      United States           Senior   
2             USD   81800          81800      United States           Senior   
3             USD  212000         212000      United States           Senior   
4             USD   93300          93300      United States           Senior   

  employment_type work_setting company_location company_size  
0       Full-time       Hybrid          Germany            L  
1       Full-time    In-person    United States            M  
2       Full-time    In-person    United States            M  
3       Full-time    In-person    United States            M  
4       Full-time    In-person    United States            M

In [6]:
#son 5 satırına göz gezdirelim
df.tail()

work_year                 job_title                  job_category  \
9350       2021           Data Specialist  Data Management and Strategy   
9351       2020            Data Scientist     Data Science and Research   
9352       2021  Principal Data Scientist     Data Science and Research   
9353       2020            Data Scientist     Data Science and Research   
9354       2020     Business Data Analyst                 Data Analysis   

     salary_currency  salary  salary_in_usd employee_residence  \
9350             USD  165000         165000      United States   
9351             USD  412000         412000      United States   
9352             USD  151000         151000      United States   
9353             USD  105000         105000      United States   
9354             USD  100000         100000      United States   

     experience_level employment_type work_setting company_location  \
9350           Senior       Full-time       Remote    United States   
9351           Senior       Full-time       Remote    United States   
9352        Mid-level       Full-time       Remote    United States   
9353      Entry-level       Full-time       Remote    United States   
9354      Entry-level        Contract       Remote    United States   

     company_size  
9350            L  
9351            L  
9352            L  
9353            S  
9354            L

info() metodu, genellikle pandas kütüphanesi ile kullanılan ve bir DataFrame hakkında özet bilgi sağlayan bir fonksiyondur.

Bu özet bilgi, veri setinin genel yapısını anlamak için oldukça faydalıdır.

.info() Metodunun Sağladığı Bilgiler:

Veri Tipleri: Hangi sütunun hangi veri tipine (örneğin, int, float, object (string), datetime) sahip olduğunu gösterir.

Sütun İsimleri: Veri setindeki tüm sütunların isimlerini listeler.

Null (Eksik) Değerler: Her sütundaki eksik (null) değerlerin sayısını gösterir.

Sütun Sayısı ve Satır Sayısı: DataFrame'deki toplam satır ve sütun sayısını belirtir.

Bellek Kullanımı: DataFrame'in bellekte ne kadar yer kapladığını gösterir.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9355 entries, 0 to 9354
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   work_year           9355 non-null   int64 
 1   job_title           9355 non-null   object
 2   job_category        9355 non-null   object
 3   salary_currency     9355 non-null   object
 4   salary              9355 non-null   int64 
 5   salary_in_usd       9355 non-null   int64 
 6   employee_residence  9355 non-null   object
 7   experience_level    9355 non-null   object
 8   employment_type     9355 non-null   object
 9   work_setting        9355 non-null   object
 10  company_location    9355 non-null   object
 11  company_size        9355 non-null   object
dtypes: int64(3), object(9)
memory usage: 877.2+ KB


.describe() metodu, genellikle pandas kütüphanesi ile kullanılan ve bir DataFrame'in sayısal sütunları hakkında özet istatistiksel bilgi sağlayan bir fonksiyondur. Bu metod, veri setinin istatistiksel özelliklerini hızlı bir şekilde anlamak için oldukça kullanışlıdır.



.describe() Metodunun Sağladığı Bilgiler:

count: Her sütundaki toplam veri noktası sayısını gösterir.

mean: Her sütunun ortalama değerini hesaplar.

std: Her sütunun standart sapmasını gösterir.

min: Her sütundaki en küçük değeri belirtir.

25% (1. çeyrek): Her sütundaki değerlerin %25'inin altında kaldığı değeri gösterir.

50% (Medyan): Her sütundaki değerlerin %50'sinin altında kaldığı değeri belirtir (medyan).

75% (3. çeyrek): Her sütundaki değerlerin %75'inin altında kaldığı değeri gösterir.

max: Her sütundaki en büyük değeri belirtir.

In [8]:
df.describe()

work_year         salary  salary_in_usd
count  9355.000000    9355.000000    9355.000000
mean   2022.760449  149927.981293  150299.495564
std       0.519470   63608.835387   63177.372024
min    2020.000000   14000.000000   15000.000000
25%    2023.000000  105200.000000  105700.000000
50%    2023.000000  143860.000000  143000.000000
75%    2023.000000  187000.000000  186723.000000
max    2023.000000  450000.000000  450000.000000

isnull(): Bu metod, bir DataFrame veya Serideki her bir değerin eksik olup olmadığını kontrol eder ve aynı boyutta bir DataFrame veya Seri döndürür.

any(): Bu metod, eksik değerler için True olan sütunların olup olmadığını kontrol eder. Her sütun için herhangi bir True değeri varsa, o sütun için True döner.

In [9]:
df.isnull().any()

work_year             False
job_title             False
job_category          False
salary_currency       False
salary                False
salary_in_usd         False
employee_residence    False
experience_level      False
employment_type       False
work_setting          False
company_location      False
company_size          False
dtype: bool

In [10]:
df.isnull().sum()

work_year             0
job_title             0
job_category          0
salary_currency       0
salary                0
salary_in_usd         0
employee_residence    0
experience_level      0
employment_type       0
work_setting          0
company_location      0
company_size          0
dtype: int64

.unique() Metodu:
Amacı: Bir Seri veya DataFrame'in belirli bir sütunundaki benzersiz (tekrarsız) değerleri döndürür.

Kullanım Alanı: Veri setinde hangi değerlerin bulunduğunu ve tekrar eden değerleri görmek için kullanılır.

Dönüş Değeri: Benzersiz değerleri içeren bir NumPy array döndürür.

In [11]:
df.head()

work_year             job_title                    job_category  \
0       2023  Data DevOps Engineer                Data Engineering   
1       2023        Data Architect  Data Architecture and Modeling   
2       2023        Data Architect  Data Architecture and Modeling   
3       2023        Data Scientist       Data Science and Research   
4       2023        Data Scientist       Data Science and Research   

  salary_currency  salary  salary_in_usd employee_residence experience_level  \
0             EUR   88000          95012            Germany        Mid-level   
1             USD  186000         186000      United States           Senior   
2             USD   81800          81800      United States           Senior   
3             USD  212000         212000      United States           Senior   
4             USD   93300          93300      United States           Senior   

  employment_type work_setting company_location company_size  
0       Full-time       Hybrid          Germany            L  
1       Full-time    In-person    United States            M  
2       Full-time    In-person    United States            M  
3       Full-time    In-person    United States            M  
4       Full-time    In-person    United States            M

In [13]:
df["work_year"].unique()

array([2023, 2022, 2020, 2021])

In [14]:
df["salary_currency"].unique()

array(['EUR', 'USD', 'GBP', 'CAD', 'AUD', 'PLN', 'BRL', 'TRY', 'CHF',
       'SGD', 'DKK'], dtype=object)

In [16]:
df["company_size"].unique()

array(['L', 'M', 'S'], dtype=object)

.value_counts() Metodu:

Amacı: Bir Seri içindeki benzersiz değerlerin frekansını (kaç kez tekrar ettiklerini) sayar.

Kullanım Alanı: Kategorik verilerin dağılımını ve her bir değerin ne sıklıkta tekrarlandığını görmek için kullanılır.

Dönüş Değeri: Benzersiz değerleri ve bunların frekanslarını içeren bir pandas Seri döndürür, sıklıkla azalan düzende sıralanır.

In [17]:
df["work_year"].value_counts()

work_year
2023    7453
2022    1634
2021     197
2020      71
Name: count, dtype: int64

In [18]:
df['company_size'].value_counts()

company_size
M    8448
L     748
S     159
Name: count, dtype: int64

.groupby() Metodu:

Amacı: Bir DataFrame'i belirtilen bir veya daha fazla sütuna göre gruplar ve bu gruplar üzerinde toplu işlemler (aggregate functions) gerçekleştirilmesini sağlar.

Kullanım Alanı: Veriyi gruplar halinde özetlemek, analiz etmek ve toplu işlemler yapmak için kullanılır.
Syntax: df.groupby('sütun_adı')

In [19]:
df.groupby("work_year")[["salary_in_usd"]].mean().reset_index()

work_year  salary_in_usd
0       2020  105878.859155
1       2021  106483.644670
2       2022  135467.501836
3       2023  155132.591708

In [20]:
df.head()

work_year             job_title                    job_category  \
0       2023  Data DevOps Engineer                Data Engineering   
1       2023        Data Architect  Data Architecture and Modeling   
2       2023        Data Architect  Data Architecture and Modeling   
3       2023        Data Scientist       Data Science and Research   
4       2023        Data Scientist       Data Science and Research   

  salary_currency  salary  salary_in_usd employee_residence experience_level  \
0             EUR   88000          95012            Germany        Mid-level   
1             USD  186000         186000      United States           Senior   
2             USD   81800          81800      United States           Senior   
3             USD  212000         212000      United States           Senior   
4             USD   93300          93300      United States           Senior   

  employment_type work_setting company_location company_size  
0       Full-time       Hybrid          Germany            L  
1       Full-time    In-person    United States            M  
2       Full-time    In-person    United States            M  
3       Full-time    In-person    United States            M  
4       Full-time    In-person    United States            M

In [21]:
df.groupby("job_category")[["salary_in_usd"]].mean().reset_index()

job_category  salary_in_usd
0            BI and Visualization  135092.102236
1              Cloud and Database  155000.000000
2                   Data Analysis  108505.721345
3  Data Architecture and Modeling  156002.359073
4                Data Engineering  146197.656195
5    Data Management and Strategy  103139.934426
6     Data Quality and Operations  100879.472727
7       Data Science and Research  163758.575979
8       Leadership and Management  145476.019881
9         Machine Learning and AI  178925.847339

In [22]:
df.groupby("job_category")[["salary_in_usd"]].mean().sort_values(by="salary_in_usd",ascending=False).reset_index()

job_category  salary_in_usd
0         Machine Learning and AI  178925.847339
1       Data Science and Research  163758.575979
2  Data Architecture and Modeling  156002.359073
3              Cloud and Database  155000.000000
4                Data Engineering  146197.656195
5       Leadership and Management  145476.019881
6            BI and Visualization  135092.102236
7                   Data Analysis  108505.721345
8    Data Management and Strategy  103139.934426
9     Data Quality and Operations  100879.472727